//
// BWEAS is distributed under the gnu general public license 2.0 (gpl-2.0).
// you can view the license text at the link:
//     <https://www.gnu.org/licenses>
// ------------------------------------------
//

#ifndef BWGENERATOR_HPP
#define BWGENERATOR_HPP

#include <functional>
#include <string_view>

#include "bw_defs.hpp"
#include "bwdepends_files.hpp"
#include "bwluatools.hpp"

namespace bweas {

namespace generator_api {

struct data_transfer;
struct command;

class interface_generator;
class base_generator;
class integral_generator;
class lua_generator;

// name_templates, name files
using files_input = map<string, vec<string>>;
// name_input_file, command
using commands = vec<command>;

using func_generator                = std::function<commands(data_transfer &)>;
using func_build_graph_depends_file = std::function<uset<string>(string_v, string_v, string_v, vec<string>)>;
using func_get_input_files          = std::function<void(data_transfer &)>;

} // namespace generator_api
} // namespace bweas

// A temporary structure that allows you to transfer data to the generator and its sub-functions
struct bweas::generator_api::data_transfer {
    data_transfer(bw_context *const _context, string _work_directory)
        : context(_context), work_directory(_work_directory) {
    }

  public:
    bw_context *const context;

    depends_files::depends_map dfiles;
    files_input ifiles;
    string work_directory;
};

struct bweas::generator_api::command {
  public:
    command() = default;
    command(string_v _name_used_file, string_v _name_program, vec<string> _args)
        : name_used_file(_name_used_file), name_program(_name_program), args(_args) {
    }

  public:
    string name;
    string name_used_file;
    string name_program;

    vec<string> args;
    vec<string> depends_command;

  public:
    size_t pid_execute_process = 0;
    bool success               = 0;
};

// Interface class that defines the structure of generator classes
class bweas::generator_api::interface_generator {
  private:
    interface_generator &operator=(const interface_generator &) = delete;

  public:
    virtual ~interface_generator() = default;

  public:
    // Generator initialization function
    virtual void init() = 0;

    // Implementing a function for the file dependency system, returns a list of dependent files(graph)
    virtual uset<string> build_graph_depends_file(string_v, string_v, string_v, vec<string>) = 0;
    // Initializes(defines) files that should be compiled (recompiled) for the current target
    virtual void get_input_files(data_transfer &) = 0;
    // The generator function returns the commands generated by it in the order of the templates used for the
    // transmitted target
    virtual commands generate_commands(data_transfer &) = 0;
};

// An abstract class that defines the creation of generator classes and is also a generalization
class bweas::generator_api::base_generator : public bweas::generator_api::interface_generator {
  public:
    ~base_generator() = default;

  public:
    void set_use_build_graph_depends() {
        use_build_graph_depends = 1;
    }

    bool has_build_graph_depends() {
        return use_build_graph_depends;
    }

  public:
    static inline base_generator *create_generator_int(func_build_graph_depends_file, func_get_input_files,
                                                       func_generator);
    static inline base_generator *create_generator_lua(string_v);

  public:
    static bool is_exist(base_generator *generator) {
        if (!generator)
            return 0;
        return 1;
    }

  private:
    bool use_build_graph_depends{0};
};

// The class defines the API for internal generators, i.e. built into bweas as basic
class bweas::generator_api::integral_generator final : public bweas::generator_api::base_generator {
    friend base_generator *base_generator::create_generator_int(func_build_graph_depends_file, func_get_input_files,
                                                                func_generator);

  private:
    integral_generator(func_build_graph_depends_file, func_get_input_files, func_generator);

  public:
    ~integral_generator() = default;

  public:
    void init() override;

    uset<string> build_graph_depends_file(string_v language, string_v name_file, string_v work_directory,
                                          vec<string> include_paths) override;
    void get_input_files(data_transfer &data_t) override;
    commands generate_commands(data_transfer &data_t) override;

  private:
    func_build_graph_depends_file build_graph_depends_file_p;
    func_get_input_files get_input_files_p;
    func_generator generate_p;
};

// The class defines the API for generators written in lua and presented in bweas packages
class bweas::generator_api::lua_generator final : public bweas::generator_api::base_generator {
    friend base_generator *base_generator::create_generator_lua(string_v);

  private:
    lua_generator(string_v);

  public:
    ~lua_generator() = default;

  public:
    void init() override;

    uset<string> build_graph_depends_file(string_v language, string_v name_file, string_v work_directory,
                                          vec<string> include_paths) override;
    void get_input_files(data_transfer &data_t) override;
    commands generate_commands(data_transfer &data_t) override;

  private:
    bwlua::lua lua;
};
bweas::generator_api::base_generator *bweas::generator_api::base_generator::create_generator_int(
    func_build_graph_depends_file build_graph_depends_file, func_get_input_files get_input_files,
    func_generator generate) {
    return dynamic_cast<base_generator *>(new integral_generator(build_graph_depends_file, get_input_files, generate));
}
bweas::generator_api::base_generator *bweas::generator_api::base_generator::create_generator_lua(string_v src_lua) {
    return dynamic_cast<base_generator *>(new lua_generator(src_lua));
}

#endif
